# name: End-to-end tests using Cypress Docker Image
# on:
#   # Trigger the workflow on push request
#   # but only for the main branch
#   push:
#     branches:
#       - main

# jobs:
#   cypress-run:
#     runs-on: windows-latest
    
#     name: E2E on Chrome
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       # - name: Clean and create
#       #     run: npm run create
      
#       - name: Cypress run
#         uses: cypress-io/github-action@v2.9.7
#         with:
#           browser: chrome


name: Generate Cypress Report
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 87
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          continue-on-error: true

      - name: Create directory
        run: |
          mkdir public
          
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
