
name: Generate Cypress Report
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 87
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        continue-on-error: true
        with:
          browser: chrome

      - name: Create directory
        run: |
          mkdir public
          
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
